#!/bin/bash
set -e

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source "$SCRIPT_DIR/stack-common.sh"

REPO_ROOT=$(get_stack_repo_root)

# Configure Dify API env
API_ENV="$REPO_ROOT/runtime/dify/api/.env"
API_EXAMPLE="$REPO_ROOT/runtime/dify/api/.env.example"

if [ ! -f "$API_ENV" ] && [ -f "$API_EXAMPLE" ]; then
    echo "Creating api/.env"
    cp "$API_EXAMPLE" "$API_ENV"
    
    # Use sed to update VECTOR_STORE
    sed -i 's/^VECTOR_STORE=.*/VECTOR_STORE=qdrant/' "$API_ENV"
    echo "QDRANT_URL=http://127.0.0.1:6333" >> "$API_ENV"
    
    # DB settings
    sed -i 's/^DB_HOST=.*/DB_HOST=127.0.0.1/' "$API_ENV"
    sed -i 's/^DB_PORT=.*/DB_PORT=5433/' "$API_ENV"
    
    # Plugin Daemon settings
    sed -i 's/^PLUGIN_DAEMON_URL=.*/PLUGIN_DAEMON_URL=http:\/\/127.0.0.1:5002/' "$API_ENV"

    # Redis — chạy không password, xóa default password từ .env.example
    sed -i 's/^REDIS_PASSWORD=.*/REDIS_PASSWORD=/' "$API_ENV"
    sed -i 's/^BROKER_USE_SSL=.*/BROKER_USE_SSL=false/' "$API_ENV"
    sed -i 's/^CELERY_BROKER_URL=.*/CELERY_BROKER_URL=redis:\/\/localhost:6379\/1/' "$API_ENV"

    # Console URL — Dify Web chạy trên 3001, không phải 3000 (mặc định Dify)
    sed -i 's/^CONSOLE_WEB_URL=.*/CONSOLE_WEB_URL=http:\/\/localhost:3001/' "$API_ENV"
    sed -i 's/^CONSOLE_CORS_ALLOW_ORIGINS=.*/CONSOLE_CORS_ALLOW_ORIGINS=http:\/\/localhost:3001/' "$API_ENV"

    # SECRET_KEY — phải cố định, nếu không tokens bị reset mỗi lần restart
    EXISTING_KEY=$(grep -oP '^SECRET_KEY=\K.+' "$API_ENV" 2>/dev/null || true)
    if [ -z "$EXISTING_KEY" ] || echo "$EXISTING_KEY" | grep -q "^sk-"; then
        NEW_KEY=$(openssl rand -base64 42)
        sed -i "s|^SECRET_KEY=.*|SECRET_KEY=${NEW_KEY}|" "$API_ENV"
        echo "  Generated new SECRET_KEY for Dify API."
    fi
fi

# Configure Dify Web env
WEB_ENV="$REPO_ROOT/runtime/dify/web/.env.local"
WEB_EXAMPLE="$REPO_ROOT/runtime/dify/web/.env.example"

if [ ! -f "$WEB_ENV" ] && [ -f "$WEB_EXAMPLE" ]; then
    echo "Creating web/.env.local"
    cp "$WEB_EXAMPLE" "$WEB_ENV"
    
    sed -i 's/^NEXT_PUBLIC_API_PREFIX=.*/NEXT_PUBLIC_API_PREFIX=http:\/\/127.0.0.1:5001\/console\/api/' "$WEB_ENV"
    sed -i 's/^NEXT_PUBLIC_PUBLIC_API_PREFIX=.*/NEXT_PUBLIC_PUBLIC_API_PREFIX=http:\/\/127.0.0.1:5001\/api/' "$WEB_ENV"
fi

# Configure Chatbot Frontend env
FRONTEND_ENV="$REPO_ROOT/frontend/.env.local"
FRONTEND_EXAMPLE="$REPO_ROOT/frontend/.env.local.example"

if [ ! -f "$FRONTEND_ENV" ] && [ -f "$FRONTEND_EXAMPLE" ]; then
    echo "Creating frontend/.env.local"
    cp "$FRONTEND_EXAMPLE" "$FRONTEND_ENV"
    
    # Generate a random 32-byte base64 string for SESSION_SECRET
    RANDOM_SECRET=$(openssl rand -base64 32)
    # Use | as delimiter for sed to avoid issues with / or + in base64
    sed -i "s|^SESSION_SECRET=.*|SESSION_SECRET=${RANDOM_SECRET}|" "$FRONTEND_ENV"

    # Configure Dify connection (without this, frontend runs in mock mode)
    sed -i "s|^DIFY_BASE_URL=.*|DIFY_BASE_URL=http://127.0.0.1:5001|" "$FRONTEND_ENV"

    # DIFY_USE_MOCK is not in .env.local.example, so append it
    if ! grep -q "^DIFY_USE_MOCK=" "$FRONTEND_ENV"; then
        echo "DIFY_USE_MOCK=false" >> "$FRONTEND_ENV"
    else
        sed -i "s|^DIFY_USE_MOCK=.*|DIFY_USE_MOCK=false|" "$FRONTEND_ENV"
    fi
    echo "  NOTE: Set DIFY_API_KEY in frontend/.env.local after creating a Dify App."
    echo "  Get the key from: Dify → App → API Access → API Key"
fi

# Configure Plugin Daemon env
PLUGIN_ENV="$REPO_ROOT/runtime/ubuntu-stack/plugin-daemon.env"
PLUGIN_STORAGE="$REPO_ROOT/runtime/ubuntu-stack/data/plugin-daemon"
PLUGIN_PYTHON=$(command -v python3 || echo "/usr/bin/python3")

if [ ! -f "$PLUGIN_ENV" ]; then
    echo "Creating plugin-daemon.env"
    mkdir -p "$PLUGIN_STORAGE/storage" "$PLUGIN_STORAGE/plugin" "$PLUGIN_STORAGE/cwd" "$PLUGIN_STORAGE/persistence"

    # Read PLUGIN_DAEMON_KEY from dify api .env if it exists, otherwise use default
    DIFY_INNER_API_KEY="QaHbTe77CtuXmsfyhR7+vRjI/+XbV1AaFy691iy+kGDv2Jvy0/eAh8Y1"
    if [ -f "$API_ENV" ]; then
        # Try to read PLUGIN_DAEMON_KEY from Dify API .env
        FOUND_KEY=$(grep -oP '^PLUGIN_DAEMON_KEY=\K.*' "$API_ENV" 2>/dev/null || true)
        if [ -n "$FOUND_KEY" ]; then
            DIFY_INNER_API_KEY="$FOUND_KEY"
        fi
    fi

    cat > "$PLUGIN_ENV" <<ENVEOF
# Auto-generated by configure-dify-env.sh
SERVER_HOST=127.0.0.1
SERVER_PORT=5002
SERVER_KEY=lYkiYYT6owG+71oLerGzA7GXCgOT++6ovaezWAjpCjf+Sjc3ZtU+qUEi
GIN_MODE=release
PLATFORM=local

DIFY_INNER_API_KEY=${DIFY_INNER_API_KEY}
DIFY_INNER_API_URL=http://127.0.0.1:5001

PLUGIN_REMOTE_INSTALLING_ENABLED=true
PLUGIN_REMOTE_INSTALLING_HOST=127.0.0.1
PLUGIN_REMOTE_INSTALLING_PORT=5003

PLUGIN_STORAGE_TYPE=local
PLUGIN_STORAGE_LOCAL_ROOT=${PLUGIN_STORAGE}/storage
PLUGIN_INSTALLED_PATH=${PLUGIN_STORAGE}/plugin
PLUGIN_WORKING_PATH=${PLUGIN_STORAGE}/cwd
PERSISTENCE_STORAGE_PATH=${PLUGIN_STORAGE}/persistence

REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

DB_TYPE=postgresql
DB_USERNAME=postgres
DB_PASSWORD=difyai123456
DB_HOST=127.0.0.1
DB_PORT=5433
DB_DATABASE=dify_plugin
DB_SSL_MODE=disable

MAX_PLUGIN_PACKAGE_SIZE=52428800
PYTHON_ENV_INIT_TIMEOUT=120
ROUTINE_POOL_SIZE=1024
FORCE_VERIFYING_SIGNATURE=false

PLUGIN_WEBHOOK_ENABLED=true
DIFY_INVOCATION_CONNECTION_IDLE_TIMEOUT=120
LOG_OUTPUT_FORMAT=text
ENVEOF
    echo "  Written: $PLUGIN_ENV"
fi

# Note: RAGFlow config removed in v3.3 (Full Dify architecture)

echo "Environment configuration complete."

